config/routes.rb
Tk::Application.routes.draw do
  namespace :chengs do
    resources :jzs do
      collection do
        get :fetch_1010jz
      end
    end
  end

  resources :clients

  resources :xus

end

app/models/chengs.rb
module Chengs
  def self.table_name_prefix
    'chengs_'
  end
end

app/models/chengs/jz.rb
# encoding: UTF-8
module Chengs
  class Jz < ActiveRecord::Base
    def self.fetch_1010jz
      Nokogiri::HTML(HTTPClient.get_content("http://sh.1010jz.com/")).css(
          "table.tablepix td a, table.tablepix_right td a").each do |link_a|
        link = link_a.attr("href")
        next if not link[/^http\:\/\//]
        clnt = HTTPClient.new
        doc = Nokogiri::HTML(clnt.get_content(link))
        l_info = doc.css("div.d_left").inner_html.encode("UTF-8")
        r_info = doc.css("div.d_right").inner_html.encode("UTF-8")
        jz = Jz.new
        jz.path = ""; doc.css("div.head>a").each { |l| jz.path << "/#{l.text}" }
        jz.title = doc.css("div.d_left>h2").first.text
        jz.time = l_info[/发布时间：([^<]*)/, 1]
        jz.user_name = r_info[/用户昵称：([^<]*)/, 1]
        jz.user_credit = r_info[/用户信用：([^<]*)/, 1]
        jz.user_type = r_info[/用户信用：([^<]*)/, 1]
        jz.user_date = r_info[/注册日期：([^<]*)/, 1]
        jz.user_ip = r_info[/发布人IP：([^<]*)/, 1]
        jz.company = l_info[/公司名称：([^<]*)/, 1]
        jz.info_id = l_info[/信息编号：([^\s]*)/, 1]
        next if Jz.where(info_id: jz.info_id).exists?
        jz.content = doc.css("div.d_content").inner_html.encode("UTF-8")
        img = doc.css("div.d_content>img").last
        img_path = "/assets/img/mobiles/#{jz.info_id}.jpg"
        File.open("#{XmhWeb::Application.config.paths["public"].first
            }#{img_path}", "wb") do |f|
          jz.mobile_img = img_path
          f.write clnt.get_content(URI::join(link, URI::encode(
            img.attr("src"))).to_s, nil, { Referer: link,
              "User-Agent" => "Opera/9.80 Presto/2.10.229 Version/11.61" })
        end if img
        jz.save
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/chengs/jzs_controller.rb
# encoding: UTF-8
module Chengs
  class JzsController < ApplicationController
    # GET /chengs/jzs
    # GET /chengs/jzs.json
    def index
      @title = "兼职信息列表"
      @chengs_jzs = Jz.find(:all, order: "id DESC")

      respond_to do |format|
        format.html { render layout: "cheng" }
        format.json { render json: @chengs_jzs }
      end
    end

    def fetch_1010jz
      Jz.fetch_1010jz

      respond_to { |fmt| fmt.json { render json: { result: true } } }
    end

    # GET /chengs/jzs/1
    # GET /chengs/jzs/1.json
    def show
      @chengs_jz = Chengs::Jz.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @chengs_jz }
      end
    end

    # GET /chengs/jzs/new
    # GET /chengs/jzs/new.json
    def new
      @chengs_jz = Chengs::Jz.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @chengs_jz }
      end
    end

    # GET /chengs/jzs/1/edit
    def edit
      @chengs_jz = Chengs::Jz.find(params[:id])
    end

    # POST /chengs/jzs
    # POST /chengs/jzs.json
    def create
      @chengs_jz = Chengs::Jz.new(params[:chengs_jz])

      respond_to do |format|
        if @chengs_jz.save
          format.html { redirect_to @chengs_jz, notice: 'Jz was successfully created.' }
          format.json { render json: @chengs_jz, status: :created, location: @chengs_jz }
        else
          format.html { render action: "new" }
          format.json { render json: @chengs_jz.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /chengs/jzs/1
    # PUT /chengs/jzs/1.json
    def update
      @chengs_jz = Chengs::Jz.find(params[:id])

      respond_to do |format|
        if @chengs_jz.update_attributes(params[:chengs_jz])
          format.html { redirect_to @chengs_jz, notice: 'Jz was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @chengs_jz.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /chengs/jzs/1
    # DELETE /chengs/jzs/1.json
    def destroy
      @chengs_jz = Chengs::Jz.find(params[:id])
      @chengs_jz.destroy

      respond_to do |format|
        format.html { redirect_to chengs_jzs_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
  end

  def show
    @client = { params[:id] => request.env[params[:id]] }
    @client = request.env if params[:id] == "all"
  end

end

app/controllers/xus_controller.rb
# encoding: UTF-8
class XusController < ApplicationController
  def index
    @title = "首页"

    render layout: "xu"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    @title ? @title : ""
  end
end

app/helpers/chengs/jzs_helper.rb
module Chengs::JzsHelper
  def jzsite
    params[:jzsite] || "1010jz"
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/chengs/jzs/_form.html.erb
<%= form_for(@chengs_jz) do |f| %>
  <% if @chengs_jz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chengs_jz.errors.count, "error") %> prohibited this chengs_jz from being saved:</h2>

      <ul>
      <% @chengs_jz.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :path %><br />
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :user_credit %><br />
    <%= f.text_field :user_credit %>
  </div>
  <div class="field">
    <%= f.label :user_type %><br />
    <%= f.text_field :user_type %>
  </div>
  <div class="field">
    <%= f.label :user_date %><br />
    <%= f.text_field :user_date %>
  </div>
  <div class="field">
    <%= f.label :user_ip %><br />
    <%= f.text_field :user_ip %>
  </div>
  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :info_id %><br />
    <%= f.text_field :info_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br />
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :mobile_img %><br />
    <%= f.text_field :mobile_img %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chengs/jzs/edit.html.erb
<h1>Editing chengs_jz</h1>

<%= render 'form' %>

<%= link_to 'Show', @chengs_jz %> |
<%= link_to 'Back', chengs_jzs_path %>

app/views/chengs/jzs/index.html.erb
<table class="table table-striped">
  <tr>
    <th>Path</th>
    <th>Title</th>
    <th>发布时间</th>
    <th>User name</th>
    <th>Company</th>
    <th>Mobile</th>
    <th>Mobile img</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @chengs_jzs.each do |chengs_jz| %><tr>
  <td><%= chengs_jz.path.sub(/^\/上海1010兼职网/, '1010jz') %></td>
  <td><%= chengs_jz.title %></td>
  <td style="white-space: pre;"><%= chengs_jz.time %></td>
  <td><%= chengs_jz.user_name %></td>
  <td><%= chengs_jz.company %></td>
  <td><%= chengs_jz.mobile %></td>
  <td style="padding: 0; vertical-align: middle;"><% if chengs_jz.mobile_img 
      %><img src="<%= chengs_jz.mobile_img %>" /><% end %></td>
  <td><%= link_to 'Show', chengs_jz %></td>
  <td><%= link_to 'Edit', edit_chengs_jz_path(chengs_jz) %></td>
  <td><%= link_to 'Destroy', chengs_jz, confirm: 'Are you sure?',
           method: :delete %></td></tr>
<% end %>
</table>
<a style="position: absolute; right: 9px; top: 9px;"
    href="javascript:fetch_<%= jzsite %>()">立即更新</a>

app/views/chengs/jzs/new.html.erb
<h1>New chengs_jz</h1>

<%= render 'form' %>

<%= link_to 'Back', chengs_jzs_path %>

app/views/chengs/jzs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Path:</b>
  <%= @chengs_jz.path %>
</p>

<p>
  <b>Title:</b>
  <%= @chengs_jz.title %>
</p>

<p>
  <b>Time:</b>
  <%= @chengs_jz.time %>
</p>

<p>
  <b>User name:</b>
  <%= @chengs_jz.user_name %>
</p>

<p>
  <b>User credit:</b>
  <%= @chengs_jz.user_credit %>
</p>

<p>
  <b>User type:</b>
  <%= @chengs_jz.user_type %>
</p>

<p>
  <b>User date:</b>
  <%= @chengs_jz.user_date %>
</p>

<p>
  <b>User ip:</b>
  <%= @chengs_jz.user_ip %>
</p>

<p>
  <b>Company:</b>
  <%= @chengs_jz.company %>
</p>

<p>
  <b>Info:</b>
  <%= @chengs_jz.info_id %>
</p>

<p>
  <b>Content:</b>
  <%= @chengs_jz.content %>
</p>

<p>
  <b>Mobile:</b>
  <%= @chengs_jz.mobile %>
</p>

<p>
  <b>Mobile img:</b>
  <%= @chengs_jz.mobile_img %>
</p>


<%= link_to 'Edit', edit_chengs_jz_path(@chengs_jz) %> |
<%= link_to 'Back', chengs_jzs_path %>

app/views/clients/index.html.erb
<%=raw request.env["HTTP_X_FORWARDED_FOR"] %>

app/views/clients/show.html.erb
<h1>Clients#show</h1>
<% @client.each do |c| %>
<p><%= c.first %>: <%= c.last %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tk</title>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/cheng.html.erb
<!DOCTYPE html>
<html>
<meta charset="UTF-8" />
<title>小程老师想要的<%= title %></title>
<link href="http://assets.51pass.org/css/bootstrap_v2.css" rel="stylesheet" />

<%= yield %>

<script src="http://assets.51pass.org/js/jquery.min.js"></script>
<script src="http://assets.51pass.org/js/rails.js"></script>
<script src="http://assets.51pass.org/js/jquery.tablesorter.min.js"></script>
<script>
function fetch_1010jz() {
  $.getJSON("/chengs/jzs/fetch_1010jz.json?ts=" + new Date().getTime(),
      function(data) { if (!data.result) alert("!!!") }); }

$(function() {
  $("table.table-striped").tablesorter({ sortList: [[0, 0]] });
});
</script>

app/views/layouts/xu.html.erb
<!DOCTYPE html>
<html>
<meta charset="UTF-8" />
<title>许明浩要的网站<%= title %></title>
<link href="/assets/css/xus/home.css" rel="stylesheet" />

<div id="header"><div class="bound"><a id="logo" href="#"
    style='margin-top: 20px; padding-left: 50px;
      font-size: 24px; font-weight: bold; letter-spacing: .03em; color: #222;
      font-family: "Century Gothic","Helvetica Neue",helvetica,arial,sans-serif'
    >LOGO</a>
  <div class="topnav">
    <div class="log">
      <a href="#">Global</a>
      <img src="/assets/img/xus/hw_000470.gif" />
      <a id="worldWide" href="#">选择区域/语言</a><img 
          src="/assets/img/xus/hw_092793.gif" class="arrow" />
      <img src="/assets/img/xus/hw_000470.gif">
      <a href="#">个性化服务</a>
      <span style="display:none" id="sslogoff">
        <img src="/assets/img/xus/hw_000470.gif" />
        <a id="aLogout">退出</a></span>  
      <span id="sslogon"><a id="aLogin">登录</a></span>
      <img src="/assets/img/xus/hw_000470.gif" />
      <a href="#">心声社区</a>        
    </div><!-- /log -->
    <div class="alone">
      <div id="search_1" class="search">
        <form name="SEARCH_BOX" id="SEARCH_BOX" method="post" action="#">
          <input type="text" name="ssUserText" aria-haspopup="true"
              onkeypress="if(event.keyCode=='13') return(Usearch());"
              class="text ui-autocomplete-input" id="search-box-h"
              autocomplete="off" role="textbox" aria-autocomplete="list" />
          <a id="searchButton" title="Search" href="#"></a>
        </form>
      </div><div class="auto"><div class="ico"></div>
      <div class="List_Box"><ul class="List_Box_Ul"></ul></div></div>
    </div><!-- /search -->
  </div><!-- /alone -->
</div><!-- /bound --></div><!-- /header -->
<div id="menu"><div class="bound">
  <li class="solutions"><a href="#"></a></li>
  <li class="products"><a href="#"></a></li>
  <li class="services"><a href="#"></a></li>
  <li class="support"><a href="#"></a></li>
  <li class="about"><a href="#"></a></li>
</div><!-- /bound --></div><!-- /menu -->
<div id="menu-popup" style="top: -1000px; left: 184.5px;">
  <div class="popup solutions" style="display: none;">
    <div class="menu_content"><div>
      <ul class="Arpu">
        <li class="img"><a href="#"><img src="/assets/img/xus/a_cn.gif"
            alt="Arpu up"></a></li>
        <li><a href="#">云计算</a></li>
        <li><a href="#">SDP</a></li>
        <li><a href="#">NGBSS</a></li>
        <li><a href="#">数字家庭</a></li>
        <li><a href="#">统一通信</a></li>
      </ul>
      <ul class="Broader">
        <li class="img"><a href="#"><img src="/assets/img/xus/b_cn.gif"
            alt="Broader smarter"></a></li>
        <li><a href="#">无线接入</a></li>
        <li><a href="#">固定接入</a></li>
        <li><a href="#">IPv6</a></li>
        <li><a href="#">分组核心</a></li>
        <li><a href="#">移动宽带</a></li>
      </ul>
      <ul class="Costdown">
        <li class="img"><a href="#"><img src="/assets/img/xus/c_cn.gif"
            alt="Cost down"></a></li>
        <li><a href="#">华为Single战略</a></li>
        <li><a href="#">管理服务</a></li>
        <li><a href="#">统一核心网</a></li>
        <li><a href="#">IP可视化运维</a></li>
        <li><a href="#">用户数据管理</a></li>
      </ul>
      <ul class="Gogreener">
        <li class="img"><a href="#"><img src="/assets/img/xus/g_cn.gif"
            alt="Go greener"></a></li>
        <li><a href="#">绿色通信</a></li>
        <li><a href="#">绿色能源</a></li>
        <li><a href="#">绿色数据中心</a></li>
        <li><a href="#">绿色站点</a></li>
        <li><a href="#">流量缓存加速</a></li>
      </ul>
      <p><a class="more" href="#">更多&gt;</a></p>
    </div></div><!-- /menu_content -->
  </div><!-- /popup_solutions -->
  <div class="popup services" style="display: none;">
    <div class="menu_content">
      <div class="width">
        <div class="left nlist"><ul>
          <li class="title"><a href="#">网络集成</a></li>
          <li><a href="#">移动网络集成</a></li>
          <li><a href="#">固定网络集成</a></li>
          <li><a href="#">数据中心服务</a></li>
          <li><a href="#">站点集成</a></li>
        </ul></div>
        <div class="left alist"><ul>
          <li class="title"><a href="#">保障与管理服务</a></li>
          <li><a href="#">管理服务</a></li>
          <li><a href="#">HUAWEI SmartCare</a></li>
          <li><a href="#">网络保障服务</a></li>  
        </ul></div>
        <div class="left lelist"><ul>
          <li class="title"><a href="#">学习与发展</a></li>
          <li><a href="#">能力发展咨询</a></li>
          <li><a href="#">知识传递</a></li>
          <li><a href="#">华为认证</a></li>
        </ul></div>
        <div class="left glist"><ul>
          <li class="title"><a href="#">全球交付</a></li>
          <li><a href="#">端到端交付能力</a></li>
          <li><a href="#">多场景交付能力</a></li>
        </ul></div>
      </div><!-- /width -->
      <div class="link"><a href="#">更多&gt;</a></div>
    </div><!-- /menu_content -->
  </div><!-- /popup_services -->
  <div class="popup products" style="display: none;">
    <div class="menu_content"><div>
      <ul class="marginL65">
        <li class="img"><img src="/assets/img/xus/cloud_cn.gif"></li>
        <li><a href="#">业务与软件</a></li>
        <li><a href="#">存储与网络安全</a></li>
        <li><a href="#">OSS</a></li>
      </ul>
      <ul class="marginL60">
        <li class="img"><img src="/assets/img/xus/pipe_cn.gif"></li>
        <li><a href="#">无线接入</a></li>
        <li><a href="#">固定接入</a></li>
        <li><a href="#">能源与基础设施</a></li>
        <li><a href="#">传送网</a></li>
        <li><a href="#">数据通信</a></li>
        <li><a href="#">核心网</a></li>  
      </ul>
      <ul class="marginL77">
        <li class="img"><img src="/assets/img/xus/devcies_cn.gif"></li>
        <li><a href="#">个人终端</a></li>
        <li><a href="#">家庭终端</a></li>
        <li><a href="#">企业终端</a></li>
      </ul>
      <p><a class="more" href="#">更多&gt;</a></p>
    </div></div><!-- /menu_coutent -->
  </div><!-- /popup products -->
  <div class="popup support" style="display: none;">
    <div class="menu_content">
      <div class="width">
        <div class="left">
          <div class="support_ico"><img src="/assets/img/xus/support.gif"></div>
        </div>
        <div class="support_right">   
          <h1><a href="#">文档</a></h1>  
          <div class="search">
            <input type="text" style="width:196px" class="text"
                name="support_ssUserText" id="support_ssUserText">
            <a id="searchButton" title="Search"></a>
          </div>  
          <span>请输入产品名称，如：“M2000”</span>                    
        </div><!-- /support_right -->
      </div><!-- /width -->
      <div class="link">
        <div class="left"><a href="#">公告</a>|<a href="#">互动中心</a>|<a 
            href="#">培训</a></div>
        <div class="right"><a href="#">更多&gt;</a></div>
      </div>
    </div><!-- /menu_content -->
  </div><!-- /popup support -->
  <div class="popup about" style="display: none;">
    <div class="menu_content">
      <div class="width">
        <div class="left">
          <ul>
            <li class="title"><a href="#">公司介绍</a></li>
            <li><a href="#">愿景使命</a></li>
            <li><a href="#">公司战略</a></li>
            <li><a href="#">财务概要</a></li>
            <li><a href="#">公司治理</a></li>
            <li><a href="#">研究开发</a></li>
            <li><a href="#">发展历程</a></li>
          </ul>
        </div>
        <div class="left">
          <ul>
            <li class="title"><a href="#">社会责任</a></li>
            <li><a href="#">CSR战略与管理</a></li>
            <li><a href="#">公平经营</a></li>
            <li><a href="#">消除数字鸿沟</a></li>
            <li><a href="#">绿色环保</a></li>
            <li><a href="#">供应链</a></li>
            <li><a href="#">员工</a></li>
          </ul>
        </div>
        <div class="left">
          <ul>
            <li class="title"><a href="#">新闻媒体</a></li>
            <li><a href="#">新闻</a></li>
            <li><a href="#">媒体热点</a></li>
            <li><a href="#">图片新闻</a></li>
            <li><a href="#">产品发布信</a></li>
            <li><a href="#">产品生命周期公告</a></li>
          </ul>
        </div>
        <div class="left">
          <ul>
            <li class="title"><a href="#">公司刊物</a></li>
            <li><a href="#">《公司年报》</a></li>
            <li><a href="#">《社会责任报告》</a></li>
            <li><a href="#">《营赢》</a></li>
            <li><a href="#">《华为技术》</a></li>
            <li><a href="#">《华为服务》</a></li>
          </ul>
        </div>
      </div>
      <div class="link">
        <div class="left2"><a href="#">联系我们</a>|<a href="#"
            >Newsletter</a>|<a href="#">展会活动</a></div>
        <div class="right"><a href="#">更多&gt;</a></div>
      </div>
    </div><!-- /menu_content -->
  </div><!-- /popup_about -->
</div><!-- /menu-popup -->
<%= yield %>